### ISSUE TITLE
TypeError: cannot unpack non-iterable yara.StringMatch object

### ISSUE THREAD

**Issue by m-1-k-3** [stacscan/stacs#37]
Hi @darkarnium,

 while testing the reported issue [here](https://github.com/e-m-b-a/emba/issues/600) we were able to reproduce the following issue with different extracted firmware images:
```
┌──(kali㉿kali)-[~/Downloads/kalidocker]
└─$ sudo docker run -it --mount src=/home/kali/logs/stacs/firmware,target=/firmware,type=bind kalilinux/kali-rolling
┌──(root㉿3aedcef410ab)-[/]
└─# apt update && apt upgrade && apt install python3 python3-pip git libarchive13 libarchive-dev pybind11-dev libssl-dev -y
<snip>
─(root㉿3aedcef410ab)-[/]
└─# pip install stacs
<snip>
┌──(root㉿3aedcef410ab)-[/]
└─# git clone https://github.com/stacscan/stacs-rules.git
Cloning into 'stacs-rules'...
remote: Enumerating objects: 749, done.
remote: Counting objects: 100% (133/133), done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 749 (delta 41), reused 77 (delta 17), pack-reused 616
Receiving objects: 100% (749/749), 166.71 KiB | 2.11 MiB/s, done.
Resolving deltas: 100% (199/199), done.

┌──(root㉿3aedcef410ab)-[/]
└─# stacs --rule-pack stacs-rules/credential.json /firmware/
2023-05-08 09:24:35,561 - 5268 - [INFO] STACS running with 10 threads
2023-05-08 09:24:35,561 - 5268 - [INFO] STACS uses libarchive (licenses may be found at https://github.com/libarchive/libarchive/blob/master/COPYING)
2023-05-08 09:24:35,561 - 5268 - [INFO] STACS uses yara (licenses may be found at https://github.com/VirusTotal/yara-python/blob/master/LICENSE)
2023-05-08 09:24:35,561 - 5268 - [INFO] Attempting to load rule pack from stacs-rules/credential.json
2023-05-08 09:24:35,563 - 5268 - [INFO] Using cache directory at /tmp/1683537875563211
2023-05-08 09:24:35,563 - 5268 - [INFO] Attempting to get a list of files to scan from /firmware
2023-05-08 09:24:36,768 - 5268 - [INFO] Found 1076 files for analysis
Traceback (most recent call last):
  File "/usr/local/bin/stacs", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/stacs/scan/entrypoint/cli.py", line 143, in main
    getattr(stacs.scan.scanner, scanner).run(targets, pack, workers=threads)
  File "/usr/local/lib/python3.11/dist-packages/stacs/scan/scanner/rules.py", line 229, in run
    findings.extend(future.result())
                    ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/stacs/scan/scanner/rules.py", line 183, in matcher
    findings.extend(generate_findings(target, match))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/stacs/scan/scanner/rules.py", line 153, in generate_findings
    for offset, _, entry in match.strings:
        ^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable yara.StringMatch object
```
The used testimage can be found here https://kb.netgear.com/000060419/WNAP320-Firmware-Version-3-7-11-4

**Comment by darkarnium** [comment]
Hey @m-1-k-3 ,

Thanks once again for raising this! After a quick look, it appears that there was a breaking API change introduced in the Python Yara module in version 4.3.0. I've adjusted the version pins on this module back to 4.2.3, and removed the previous constraint of allowing any current major version to avoid this in future.

https://github.com/VirusTotal/yara-python/issues/226

I will look to update STACS to adhere to the new `StringMatch` object in future, as well as adding a few additional smoke tests during CI to catch these sorts of breaking API changes in dependencies in future.

In the mean time, version 0.5.1 should resolve this issue. The release process is running now, so this should be available on PyPi within the next 20 minutes or so:

https://github.com/stacscan/stacs/releases/tag/0.5.1

That said, as always, let me know if you're able to replicate this issue on 0.5.1.

**Comment by darkarnium** [comment]
It looks like Github are having some contention on their macOS 10.15 runner fleet, so this one is still building:

https://github.com/stacscan/stacs/actions/runs/4914580673/jobs/8776041093

**Comment by m-1-k-3** [comment]
Checked and rebuild a new EMBA image. Thanks again for your quick response and fix.
Great work as usual :)
